
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFT = 5;
  public static final int PARLEFT = 2;
  public static final int PARAMEMTRO = 8;
  public static final int PARRIGHT = 3;
  public static final int EOF = 0;
  public static final int RIGHT = 6;
  public static final int error = 1;
  public static final int FUNCTION = 7;
  public static final int PUNTOYCOMA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARLEFT",
  "PARRIGHT",
  "PUNTOYCOMA",
  "LEFT",
  "RIGHT",
  "FUNCTION",
  "PARAMEMTRO"
  };
}

