/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Errores.MiError;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emely
 */
public class TablaErrores extends javax.swing.JFrame {

    /**
     * Creates new form TablaErrores
     *
     * @param errores
     */
    //TODO cambiar tipo de dato de lista
    public TablaErrores(ArrayList<MiError> errores) {
        initComponents();
        this.setSize(new Dimension(1032, 356));
        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        lb_fecha.setText("Fecha: " + dateFormat.format(date));
        lb_hora.setText(" Hora:" + hourFormat.format(date));
        if (errores != null) {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Tipo de Error");
            modelo.addColumn("Mensaje");
            //modelo.addColumn("Ubicación");
            modelo.addColumn("Linea");
            modelo.addColumn("Columna");
            errores.stream().forEach((e) -> {
                if (!e.getMensaje().equals("identificador \"null\" no identificado")) {
                    modelo.addRow(new Object[]{e.getTipo(), e.getMensaje(), e.getLinea(), e.getColumna()});
                }
            });
            jTable1.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_hora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de Errores");
        setAlwaysOnTop(true);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Reporte Generado");
        jPanel1.add(jLabel1);

        lb_fecha.setText("jLabel3");
        jPanel1.add(lb_fecha);

        lb_hora.setText("jLabel2");
        jPanel1.add(lb_hora);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_hora;
    // End of variables declaration//GEN-END:variables

}
