
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pr_a = 10;
  public static final int cadena = 19;
  public static final int par2 = 7;
  public static final int par1 = 6;
  public static final int pr_mover = 9;
  public static final int pr_hacia = 12;
  public static final int pr_izquierda = 13;
  public static final int por = 5;
  public static final int pr_la = 11;
  public static final int menos = 3;
  public static final int div = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int pr_arriba = 16;
  public static final int entero = 18;
  public static final int mas = 2;
  public static final int puntoycoma = 8;
  public static final int pr_derecha = 14;
  public static final int pr_abajo = 15;
  public static final int pr_saludar = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "div",
  "por",
  "par1",
  "par2",
  "puntoycoma",
  "pr_mover",
  "pr_a",
  "pr_la",
  "pr_hacia",
  "pr_izquierda",
  "pr_derecha",
  "pr_abajo",
  "pr_arriba",
  "pr_saludar",
  "entero",
  "cadena"
  };
}

