
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 10 19:20:16 CST 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pr_for = 18;
  public static final int cadena = 26;
  public static final int par2 = 7;
  public static final int par1 = 6;
  public static final int decimal = 25;
  public static final int not = 11;
  public static final int pr_else = 17;
  public static final int coma = 15;
  public static final int pr_if = 16;
  public static final int por = 5;
  public static final int menos = 3;
  public static final int menor = 9;
  public static final int pr_boolean = 21;
  public static final int div = 4;
  public static final int igual = 10;
  public static final int EOF = 0;
  public static final int pr_func = 23;
  public static final int pr_string = 22;
  public static final int pr_number = 20;
  public static final int error = 1;
  public static final int pr_while = 19;
  public static final int entero = 24;
  public static final int mas = 2;
  public static final int llave2 = 14;
  public static final int llave1 = 13;
  public static final int puntoycoma = 12;
  public static final int identificador = 27;
  public static final int mayor = 8;
}

