
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int DECIMAL = 9;
  public static final int UMINUS = 10;
  public static final int PARLEFT = 2;
  public static final int NUMBER = 8;
  public static final int PARRIGHT = 3;
  public static final int EOF = 0;
  public static final int ADD = 4;
  public static final int DIV = 7;
  public static final int error = 1;
  public static final int TIMES = 6;
  public static final int PUNTOYCOMA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARLEFT",
  "PARRIGHT",
  "ADD",
  "MINUS",
  "TIMES",
  "DIV",
  "NUMBER",
  "DECIMAL",
  "UMINUS",
  "PUNTOYCOMA"
  };
}

